baseURL = 'https://clemorl.fr'
title = 'Clément Orlandini'
theme = 'hugo-noir'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true 

[params]
name = "Clément Orlandini"
location = "France"
description = """
Articles, creative work, random experiments, personal and professional work, of Clément Orlandini (aka Topy, aka me).
I'm a french game designer, programmer and storyteller. While my main work involves systems design and crafting content for game studios,
I'm a tech nerd and hobbyist programmer and I strive to invent new ways to make games as well as create ambitious, intricate experiences for 
people to enjoy.
"""
profile_image = "/images/your-profile.jpg" # Place in your site's static/images/
# Social links
github = "https://github.com/clorl"
linkedin = "https://linkedin.com/in/clement-orlandini"
email = "clement.orlandini@example.com"

[languages.en]
languageName = "English"
title = "Clément Orlandini - Game Designer"
weight = 1
contentDir = "content/en"
[languages.fr]
languageName = "Français"
title = "Clément Orlandini - Game Designer"
weight = 3
contentDir = "content/fr"
